data=input("Enter a string:")
# x=slice(7)
# print(data)
# print(data[x])
# print(data.capitalize())
# print(data.title())
# print(data.upper())
# print(data.lower())
# print(data.strip())
# print(data.find("world"))
# print(data.count("hello"))
# print(data.replace("hello","hi"))
# print(data[0])
# print(len(data))
# print(data[len(data)-1])
# print(data[-1])
# print(data[1:4])
# print(data[::-1])